name: Amount of Your DMM mobile Traffic
on:
  push:
jobs:
  continuous_integration:
    name: lets_ci
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: yarn
      - name: yarn install
        run: |
          yarn install
      # cf. https://circleci.com/orbs/registry/orb/threetreeslight/puppeteer
      - name: Install Headless Chrome dependencies
        run: |
          sudo apt install -yq \
          libnss3 libdbus-1-3 libatk1.0-0 libasound2t64 libxrandr2 libxkbcommon-dev \
          libxfixes3 libxcomposite1 libxdamage1 libgbm-dev libatk-bridge2.0-0 binutils \
          libglib2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libnss3-dev libxss-dev xvfb \
          fonts-liberation libu2f-udev xdg-utils
      - name: test
        run: |
          yarn test
